# This is a basic workflow to help you get started with Actions

name: Checking code quality

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  key: value 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  job1:
    - name: Install Dependencies
      run: npm install
    
     
  job2:
    - name: Scan with Sonar Scanner
      runs-on: ubuntu-latest
      # You may pin to the exact commit or the version.
      # uses: mathrix-education/sonar-scanner@f40ca3aebb6f72ec4887de752b0d739010122504
      uses: mathrix-education/sonar-scanner@1.0.0
      with:
        # The Sonar Scanner version.
        version: 
        # Use the bundled JRE.
        with-jre: # optional, default is false
        # Default Sonar Scanner options. Read as a YAML document (you may use the pipe '|' YAML operator).
        options: # optional
        # Install TypeScript during setup (simply run `npm i typescript`). Required if your project uses Typescript and if the node module `typescript` is  not already installed.
        typescript: # optional, default is false
        # Fetch a full clone of the repository. Useful when using the SCM feature of Sonar Scanner.
        unshallow: # optional, default is false
        # Run Sonar Scanner immediately in the current working directory.
        scan: # optional, default is false
        # Additionnal flag to append during the scan. Ignored if `scan` is false.
        args: # optional
     # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
